### ISSUE TITLE
Speex decoder is vulnerable

### ISSUE THREAD

**Issue by klemensbaum** [xiph/speex#4]
### Bug description
The speex decoder in libspeex does not properly sanitize its input.

Applications using libspeex can crash when decoding bad speex frames, resulting in denial-of-service.  It may also be possible to achieve remote code execution.

This bug was initially reported as WhisperSystems/Signal-Android#6334.

### Steps to reproduce
- Write a minimal program using libspeex to decode raw speex data. You can use this one: https://gist.github.com/klemensbaum/fb7c41c981ac43a5abbb3d8fb99d3902
- Obtain some sample audio and convert it to raw speex frames. Save each frame as a separate file in a testcases directory.
- *(optional)* Prune redundant test cases with `afl-tmin`
- Run `afl-fuzz` over it: `afl-fuzz -i testcases -o findings -- ./speex-fuzz @@`

**Actual result:** `afl-fuzz` finds a lot of crashes
**Expected result:** `afl-fuzz` doesn't find any crashes

### Example crashes

Some example crashes found during a short `afl-fuzz` run: https://gist.github.com/klemensbaum/3df0260fe459c10a5adb2fd569b41dda

**Comment by erikd** [comment]
I've got some experience with AFL and I'm willing to take a look at this. Thanks @klemensbaum !

**Comment by erikd** [comment]
Ok, I had a look at this. To make it easier to work on, I converted your C++ demo program to plain C and build Speex and your program with Address Sanitizer (ASAN) to make debugging easier.

I am not the original author of the Speex code, but from what I can see, all the issues you found were due to errors in your test program.

Firstly a very small number of the test files were failing when built with  ASAN due to a missing call to `speex_decoder_destroy (dec_state)` at the the end of your program.

The second problem is that calling `speex_decode_int` in a while loop and incrementing `raw_data_offset`as you go was causing Speex to write beyond the end of `raw_data` buffer you provided to Speex. As such, I would consider this an error in the calling program.

Reading your original issue again, I suspect that you think that each input file you provided should decode to a single Speex output frame. While that may in fact be true for the original fames you provided to AFL, it most definitely is not true for the mutated versions of those single frames.  In one partcular input file you provided, I found that Speex produced three output frames before writing beyond the end of the `raw_data` buffer.

My "fixed" C version of your program is here:

```
 #include <speex/speex.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <assert.h>

static size_t
read_file (const char * filename, void * buffer, size_t buffer_size)
{	FILE * file;
	size_t len;

	memset (buffer, 0, buffer_size) ;

	if ((file = fopen (filename, "rb")) == NULL)
	{
        printf ("Reading file '%s' failed : %s\n", filename, strerror (errno));
        return EXIT_FAILURE;
	}

	len = fread (buffer, 1, buffer_size, file) ;

	fclose (file) ;

	if (len < 2)
	{
        printf ("Reading file '%s', fread returned %d\n", filename, (int) len);
        return EXIT_FAILURE;
	}

	return len;
}


int
main (int argc, char const *argv[])
{
    static char encoded_data [1024];

    if (argc < 2)
    {
        printf ("usage: %s <encoded-file>\n", argv [0]);
        return EXIT_FAILURE;
    }

    SpeexBits bits;
    void *dec_state;
    dec_state = speex_decoder_init(&speex_nb_mode);
    spx_int32_t enh = 1;
    speex_decoder_ctl(dec_state, SPEEX_SET_ENH, &enh);

    spx_int32_t frame_size;
    speex_decoder_ctl(dec_state, SPEEX_GET_FRAME_SIZE, &frame_size);

    speex_bits_init(&bits);

    size_t len = read_file (argv [1], encoded_data, sizeof (encoded_data));
    speex_bits_read_from(&bits, encoded_data, len);

    // From WebRTC:
    static const int kMaxFrameSize = 2880;  // 60 ms @ 48 kHz.
    int16_t raw_data [kMaxFrameSize] ;
    size_t raw_data_offset = 0;

    while (speex_decode_int(dec_state, &bits, raw_data + raw_data_offset) == 0)
    {
		// Don't bump raw_data_offset so each frame gets written to the same
		// buffer position. This allows us to test the invariant that all
		// output frames are < hMaxFrameSize.
        // raw_data_offset += frame_size;
    }
    assert(raw_data_offset <= sizeof(raw_data));

    speex_decoder_destroy(dec_state);

    return EXIT_SUCCESS;
}
```

**Comment by klemensbaum** [comment]
Sorry for the false alarm here.

The issue is solely in Signal's (wrong) usage of libspeex, after which the test program was modeled. In fact, there is even a comment indicating the missing bounds checking in their code: https://github.com/WhisperSystems/Signal-Android/blob/c7c411b3f354bbd5930e0c0ef9778831ecc5f329/jni/redphone/AudioCodec.cpp#L110

I will submit a patch to WhisperSystems/Signal-Android.
